# Generated by Django 2.2.5 on 2021-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210225_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='early_checkin',
            field=models.BooleanField(default=False, verbose_name='Early Check-in'),
        ),
    ]
