# Generated by Django 2.2.5 on 2021-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='item_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Item Picture'),
        ),
    ]
