# Generated by Django 2.2.5 on 2021-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopitem_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_picture',
            field=models.ImageField(blank=True, upload_to='item_picture', verbose_name='Item Picture'),
        ),
    ]
